# ex: ts=2 sw=2 sts=2 et
sudo: false

language: generic

apt:
  packages:
    - libsodium


matrix:
  include:
    # Stable channel
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=stable
      # Extra packages only for this job
      addons:
        apt:
          packages: &arm_unknown_linux_gnueabihf
            # Cross compiler and cross compiled C libraries
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
            # Emulator
            - qemu-user
    - os: osx
      env: TARGET=i686-apple-darwin CHANNEL=stable
    - os: linux
      env: TARGET=i686-unknown-linux-gnu CHANNEL=stable
      addons:
        apt:
          packages: &i686_unknown_linux_gnu
            # Cross compiler and cross compiled C libraries
            - gcc-multilib
    - os: osx
      env: TARGET=x86_64-apple-darwin CHANNEL=stable
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu CHANNEL=stable
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl CHANNEL=stable
    # Beta channel
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=beta
      addons:
        apt:
          # Use the same packages the stable version uses
          packages: *arm_unknown_linux_gnueabihf
    - os: osx
      env: TARGET=i686-apple-darwin CHANNEL=beta
    - os: linux
      env: TARGET=i686-unknown-linux-gnu CHANNEL=beta
      addons:
        apt:
          packages: *i686_unknown_linux_gnu
    - os: osx
      env: TARGET=x86_64-apple-darwin CHANNEL=beta
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu CHANNEL=beta
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl CHANNEL=beta
    # Nightly channel
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=nightly
      addons:
        apt:
          # Use the same packages the stable version uses
          packages: *arm_unknown_linux_gnueabihf
    - os: osx
      env: TARGET=i686-apple-darwin CHANNEL=nightly
    - os: linux
      env: TARGET=i686-unknown-linux-gnu CHANNEL=nightly
      addons:
        apt:
          packages: *i686_unknown_linux_gnu
    - os: osx
      env: TARGET=x86_64-apple-darwin CHANNEL=nightly
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu CHANNEL=nightly
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl CHANNEL=nightly
  allow_failures:
    # NOTE This target appears to be broken on Rust 1.7.0 and on nightlies :/
    # TODO You may want to remove this entry by the time Rust 1.8.0 is out
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=stable
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=nightly
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=beta

install:
  - export PATH="$PATH:~/multirust/bin"
  - ci/install.sh

script:
  - ci/script.sh

after_success:
  - ci/travis-doc-upload.sh

notifications:
  email:
    on_success: never
