# ex: ts=2 sw=2 sts=2 et
sudo: false
dist: focal

language: rust

apt:
  packages:
    - libsodium

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  - cargo bench --all --verbose
