# ex: ts=2 sw=2 sts=2 et
sudo: false
dist: focal

language: rust

rust:
  - beta

cache:
  ccache: true
  cargo: true

apt:
  packages:
    - libsodium

script:
  - cargo build --all --verbose
  - cargo test --all --verbose

branches:
  only:
    - staging
    - trying
    - master
