[package]
name = "sodalite"
version = "0.1.1"
authors = ["Cody P Schafer <dev@codyps.com>"]
description = "Nothing Yet"
license = "AGPL-3.0"
homepage = "https://github.com/jmesmon/sodalite"
repository = "https://github.com/jmesmon/sodalite.git"
docs = "http://codyps.com/docs/sodalite/x86_64-unknown-linux-musl/sodalite/"

[dependencies]
rand = "0.*"

[dev-dependencies]
tweetnacl = { path = "tweetnacl", version = "0.*" }
