[package]
name = "sodalite"
version = "0.2.2"
authors = ["Cody P Schafer <dev@codyps.com>"]
description = "Tweetnacl in Pure Rust"
license = "AGPL-3.0"
homepage = "https://github.com/jmesmon/sodalite"
repository = "https://github.com/jmesmon/sodalite.git"
documentation = "http://codyps.com/docs/sodalite/x86_64-unknown-linux-musl/stable/sodalite/"
keywords = [ "sodium", "crypto", "nacl" ]
readme = "README.md"
include = ["Cargo.toml", "src/*.rs" ]

[dependencies]
rand = "0.*"
index-fixed = "0.0.*"

[dev-dependencies]
tweetnacl = { path = "tweetnacl", version = "0.*" }
