[package]
name = "sodalite"
version = "0.2.4"
authors = ["Cody P Schafer <dev@codyps.com>"]
description = "Tweetnacl in Pure Rust"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/jmesmon/sodalite"
repository = "https://github.com/jmesmon/sodalite.git"
documentation = "https://docs.rs/sodalite/0.2.4/sodalite/"
keywords = [ "sodium", "crypto", "nacl" ]
readme = "README.md"
include = ["Cargo.toml", "src/*.rs" ]

[dependencies]
rand = { version = "0.*", optional = true }
index-fixed = "0.0.*"

[dev-dependencies]
tweetnacl = { path = "tweetnacl", version = "0.*" }
rand = "0.*"
