[package]
name = "sodalite"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
description = "Nothing Yet"
license = "AGPL-3.0"
homepage = "https://github.com/jmesmon/sodalite"
repository = "https://github.com/jmesmon/sodalite.git"

[dependencies]
rand = "0.*"

[dev-dependencies]
sodiumoxide = "0.*"
tweetnacl = { path = "tweetnacl", version = "0.*" }
