[package]
name = "sodalite"
version = "0.1.6"
authors = ["Cody P Schafer <dev@codyps.com>"]
description = "Tweetnacl in Pure Rust"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/jmesmon/sodalite"
repository = "https://github.com/jmesmon/sodalite.git"
documentation = "http://codyps.com/docs/sodalite/x86_64-unknown-linux-musl/sodalite/"
keywords = [ "sodium", "crypto", "nacl" ]
readme = "README.md"
include = ["Cargo.toml", "src/*.rs" ]

[dependencies]
rand = "0.*"

[dev-dependencies]
tweetnacl = { path = "tweetnacl", version = "0.*" }
